# SQL Fundamentals & Schema Design

This directory documents foundational database management concepts in PostgreSQL, including Data Definition Language (DDL), primary keys, custom identity sequences, constraints, and default values.

---

## 1. Table Creation (`CREATE TABLE`)

The script below creates an `employees` table using explicit data types and integrity rules to prevent bad or duplicate data.

### Cleaned SQL Script
```sql
-- Create the employees table safely using IF NOT EXISTS
CREATE TABLE IF NOT EXISTS public.employees (
    employees_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1234 INCREMENT BY 104),
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(150) NOT NULL,
    dept VARCHAR(50),
    salary NUMERIC(15, 2) DEFAULT 30000.00,
    start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    
    CONSTRAINT employees_pkey PRIMARY KEY (employees_id),
    CONSTRAINT employees_email_key UNIQUE (email)
);
